
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_ASSIGNMENT = 48;
  public static final int STR = 47;
  public static final int OP_GT = 36;
  public static final int INTEGER = 43;
  public static final int OP_NOT = 41;
  public static final int LPAREN = 11;
  public static final int OP_AND = 32;
  public static final int CONTINUE = 21;
  public static final int INT = 8;
  public static final int OP_UMINUS = 42;
  public static final int OP_DIV = 30;
  public static final int STATIC = 6;
  public static final int RPAREN = 12;
  public static final int OP_GEQ = 37;
  public static final int SEMICOLON = 16;
  public static final int OP_DOT = 18;
  public static final int COMMA = 17;
  public static final int CLASS = 2;
  public static final int IF = 25;
  public static final int OP_ADD = 28;
  public static final int THIS = 22;
  public static final int OP_MOD = 31;
  public static final int OP_NEQ = 39;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 49;
  public static final int TRUE = 44;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int OP_LT = 34;
  public static final int OP_MULT = 29;
  public static final int NULL = 46;
  public static final int OP_OR = 33;
  public static final int BREAK = 20;
  public static final int VOID = 7;
  public static final int LBRACK = 13;
  public static final int OP_MINUS = 40;
  public static final int OP_LEQ = 35;
  public static final int LBRACE = 4;
  public static final int ELSE = 26;
  public static final int RBRACK = 14;
  public static final int WHILE = 24;
  public static final int CLASS_ID = 3;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 19;
  public static final int OP_EQ = 38;
  public static final int STRING = 10;
  public static final int FALSE = 45;
  public static final int LENGTH = 27;
  public static final int IDENTIFIER = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "CLASS_ID",
  "LBRACE",
  "RBRACE",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "STRING",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "IDENTIFIER",
  "SEMICOLON",
  "COMMA",
  "OP_DOT",
  "EXTENDS",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "WHILE",
  "IF",
  "ELSE",
  "LENGTH",
  "OP_ADD",
  "OP_MULT",
  "OP_DIV",
  "OP_MOD",
  "OP_AND",
  "OP_OR",
  "OP_LT",
  "OP_LEQ",
  "OP_GT",
  "OP_GEQ",
  "OP_EQ",
  "OP_NEQ",
  "OP_MINUS",
  "OP_NOT",
  "OP_UMINUS",
  "INTEGER",
  "TRUE",
  "FALSE",
  "NULL",
  "STR",
  "OP_ASSIGNMENT",
  "RETURN"
  };
}

